import type { CanvasConfig } from "./types"

export const defaultCanvasConfig: CanvasConfig = {
  width: 1000,
  height: 300,
  borderRadius: 12,
  layout: "horizontal",
  previewBorder: true,
  contentPadding: 40,
  exportQuality: 2,
  exportFormat: "png",
  transparentBackground: true,
  titleSubtitleGap: 12,
  title: {
    visible: true,
    text: "NekoCanvas",
    font: "Inter, sans-serif",
    size: 42,
    weight: 700,
    color: "#ffffff",
    spacing: 12,
    shadow: false,
    letterSpacing: "0px",
    lineHeight: "1.2",
    transform: "none",
    effect: "none",
    offsetX: 0,
    offsetY: 0,
  },
  subtitle: {
    visible: true,
    text: "Create stunning GitHub repository headers with minimal effort",
    font: "Inter, sans-serif",
    size: 18,
    weight: 400,
    color: "#f8fafc",
    spacing: 0,
    shadow: false,
    letterSpacing: "0px",
    lineHeight: "1.5",
    transform: "none",
    effect: "none",
    offsetX: 0,
    offsetY: 0,
  },
  background: {
    type: "preset",
    color: "#38bdf8",
    gradientStart: "#38bdf8",
    gradientEnd: "#9e3ce7",
    gradientAngle: 135,
    pattern: "grid",
    patternBackground: "#f1f5f9",
    preset: "gradient-bluelavender",
  },
  logo: {
    visible: true,
    url: null,
    size: 80,
    shape: "circle",
    borderRadius: 8,
    position: "left",
    offsetX: 0,
    offsetY: 0,
    objectFit: "cover",
    filter: "none",
    animation: "none",
    shadow: false,
    border: false,
    borderWidth: 2,
    borderColor: "#ffffff",
    opacity: 100,
  },
}
